"""initial database schema

Revision ID: f750a105add2
Revises: 
Create Date: 2026-08-19 12:35:39.354343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f750a105add2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('total_experience_years', sa.Float(), server_default='0', nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=30), server_default='FULL_TIME', nullable=False),
    sa.Column('cost_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('availability_status', sa.String(length=30), server_default='AVAILABLE', nullable=False),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('current_utilization_percentage', sa.Float(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_availability_status'), 'employees', ['availability_status'], unique=False)
    op.create_index(op.f('ix_employees_available_from'), 'employees', ['available_from'], unique=False)
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_designation'), 'employees', ['designation'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_employment_type'), 'employees', ['employment_type'], unique=False)
    op.create_index(op.f('ix_employees_full_name'), 'employees', ['full_name'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_location'), 'employees', ['location'], unique=False)
    op.create_table('executive_kpi_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_month', sa.Date(), nullable=False),
    sa.Column('total_pipeline_value', sa.Numeric(precision=16, scale=2), server_default='0', nullable=False),
    sa.Column('forecast_revenue', sa.Numeric(precision=16, scale=2), server_default='0', nullable=False),
    sa.Column('actual_revenue', sa.Numeric(precision=16, scale=2), server_default='0', nullable=False),
    sa.Column('gross_margin_percentage', sa.Float(), server_default='0', nullable=False),
    sa.Column('win_rate', sa.Float(), server_default='0', nullable=False),
    sa.Column('resource_utilization_percentage', sa.Float(), server_default='0', nullable=False),
    sa.Column('bench_percentage', sa.Float(), server_default='0', nullable=False),
    sa.Column('account_expansion_revenue', sa.Numeric(precision=16, scale=2), server_default='0', nullable=False),
    sa.Column('partner_influenced_pipeline', sa.Numeric(precision=16, scale=2), server_default='0', nullable=False),
    sa.Column('active_opportunities', sa.Integer(), server_default='0', nullable=False),
    sa.Column('won_opportunities', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lost_opportunities', sa.Integer(), server_default='0', nullable=False),
    sa.Column('healthy_accounts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('at_risk_accounts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active_contracts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('contracts_due_for_renewal', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_employees', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_employees', sa.Integer(), server_default='0', nullable=False),
    sa.Column('allocated_employees', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pending_resource_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pending_presales_approvals', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executive_kpi_snapshots_id'), 'executive_kpi_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_executive_kpi_snapshots_snapshot_month'), 'executive_kpi_snapshots', ['snapshot_month'], unique=True)
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('partner_type', sa.String(length=50), nullable=False),
    sa.Column('partner_program', sa.String(length=150), nullable=True),
    sa.Column('partner_tier', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=150), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_contact_email'), 'partners', ['contact_email'], unique=False)
    op.create_index(op.f('ix_partners_id'), 'partners', ['id'], unique=False)
    op.create_index(op.f('ix_partners_name'), 'partners', ['name'], unique=True)
    op.create_index(op.f('ix_partners_partner_tier'), 'partners', ['partner_tier'], unique=False)
    op.create_index(op.f('ix_partners_partner_type'), 'partners', ['partner_type'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('employee_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('proficiency_level', sa.String(length=30), nullable=False),
    sa.Column('experience_years', sa.Float(), server_default='0', nullable=False),
    sa.Column('certification_name', sa.String(length=200), nullable=True),
    sa.Column('certification_number', sa.String(length=100), nullable=True),
    sa.Column('certification_expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'skill_id', name='uq_employee_skills_employee_skill')
    )
    op.create_index(op.f('ix_employee_skills_certification_expiry_date'), 'employee_skills', ['certification_expiry_date'], unique=False)
    op.create_index(op.f('ix_employee_skills_employee_id'), 'employee_skills', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_skills_id'), 'employee_skills', ['id'], unique=False)
    op.create_index(op.f('ix_employee_skills_proficiency_level'), 'employee_skills', ['proficiency_level'], unique=False)
    op.create_index(op.f('ix_employee_skills_skill_id'), 'employee_skills', ['skill_id'], unique=False)
    op.create_table('partner_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('certification_name', sa.String(length=200), nullable=False),
    sa.Column('certification_level', sa.String(length=100), nullable=True),
    sa.Column('certification_number', sa.String(length=150), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('verification_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_certifications_certification_name'), 'partner_certifications', ['certification_name'], unique=False)
    op.create_index(op.f('ix_partner_certifications_employee_id'), 'partner_certifications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_partner_certifications_expiry_date'), 'partner_certifications', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_partner_certifications_id'), 'partner_certifications', ['id'], unique=False)
    op.create_index(op.f('ix_partner_certifications_is_active'), 'partner_certifications', ['is_active'], unique=False)
    op.create_index(op.f('ix_partner_certifications_partner_id'), 'partner_certifications', ['partner_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=150), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_name', sa.String(length=150), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('account_director_id', sa.Integer(), nullable=False),
    sa.Column('annual_revenue', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('customer_health_status', sa.String(length=20), server_default='GREEN', nullable=False),
    sa.Column('nps_score', sa.Float(), nullable=True),
    sa.Column('sla_status', sa.String(length=30), nullable=True),
    sa.Column('risk_level', sa.String(length=20), server_default='LOW', nullable=False),
    sa.Column('account_status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_director_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_director_id'), 'accounts', ['account_director_id'], unique=False)
    op.create_index(op.f('ix_accounts_account_name'), 'accounts', ['account_name'], unique=True)
    op.create_index(op.f('ix_accounts_account_status'), 'accounts', ['account_status'], unique=False)
    op.create_index(op.f('ix_accounts_customer_health_status'), 'accounts', ['customer_health_status'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_industry'), 'accounts', ['industry'], unique=False)
    op.create_index(op.f('ix_accounts_primary_contact_email'), 'accounts', ['primary_contact_email'], unique=False)
    op.create_index(op.f('ix_accounts_risk_level'), 'accounts', ['risk_level'], unique=False)
    op.create_index(op.f('ix_accounts_sla_status'), 'accounts', ['sla_status'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('contact_name', sa.String(length=150), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('lead_source', sa.String(length=100), nullable=True),
    sa.Column('lead_status', sa.String(length=50), server_default='NEW', nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='MEDIUM', nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('assigned_sales_id', sa.Integer(), nullable=False),
    sa.Column('next_follow_up_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_sales_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assigned_sales_id'), 'leads', ['assigned_sales_id'], unique=False)
    op.create_index(op.f('ix_leads_company_name'), 'leads', ['company_name'], unique=False)
    op.create_index(op.f('ix_leads_contact_email'), 'leads', ['contact_email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_lead_status'), 'leads', ['lead_status'], unique=False)
    op.create_index(op.f('ix_leads_next_follow_up_date'), 'leads', ['next_follow_up_date'], unique=False)
    op.create_index(op.f('ix_leads_priority'), 'leads', ['priority'], unique=False)
    op.create_table('presales_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=150), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope_content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presales_templates_created_by'), 'presales_templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_presales_templates_id'), 'presales_templates', ['id'], unique=False)
    op.create_index(op.f('ix_presales_templates_service_type'), 'presales_templates', ['service_type'], unique=False)
    op.create_index(op.f('ix_presales_templates_template_name'), 'presales_templates', ['template_name'], unique=True)
    op.create_table('rfps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfp_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('submission_deadline', sa.Date(), nullable=False),
    sa.Column('rfp_status', sa.String(length=30), server_default='RECEIVED', nullable=False),
    sa.Column('bid_decision', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfps_bid_decision'), 'rfps', ['bid_decision'], unique=False)
    op.create_index(op.f('ix_rfps_client_name'), 'rfps', ['client_name'], unique=False)
    op.create_index(op.f('ix_rfps_id'), 'rfps', ['id'], unique=False)
    op.create_index(op.f('ix_rfps_owner_id'), 'rfps', ['owner_id'], unique=False)
    op.create_index(op.f('ix_rfps_received_date'), 'rfps', ['received_date'], unique=False)
    op.create_index(op.f('ix_rfps_rfp_number'), 'rfps', ['rfp_number'], unique=True)
    op.create_index(op.f('ix_rfps_rfp_status'), 'rfps', ['rfp_status'], unique=False)
    op.create_index(op.f('ix_rfps_service_type'), 'rfps', ['service_type'], unique=False)
    op.create_index(op.f('ix_rfps_submission_deadline'), 'rfps', ['submission_deadline'], unique=False)
    op.create_index(op.f('ix_rfps_title'), 'rfps', ['title'], unique=False)
    op.create_table('account_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_name', sa.String(length=200), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('probability', sa.Float(), server_default='0', nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='OPEN', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_opportunities_account_id'), 'account_opportunities', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_opportunities_created_by'), 'account_opportunities', ['created_by'], unique=False)
    op.create_index(op.f('ix_account_opportunities_expected_close_date'), 'account_opportunities', ['expected_close_date'], unique=False)
    op.create_index(op.f('ix_account_opportunities_id'), 'account_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_account_opportunities_opportunity_name'), 'account_opportunities', ['opportunity_name'], unique=False)
    op.create_index(op.f('ix_account_opportunities_service_type'), 'account_opportunities', ['service_type'], unique=False)
    op.create_index(op.f('ix_account_opportunities_status'), 'account_opportunities', ['status'], unique=False)
    op.create_table('bid_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfp_id', sa.Integer(), nullable=False),
    sa.Column('strategic_fit_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('technical_fit_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('resource_availability_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('profitability_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('win_probability', sa.Float(), server_default='0', nullable=False),
    sa.Column('overall_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('recommendation', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('evaluated_by', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evaluated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rfp_id'], ['rfps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_evaluations_evaluated_by'), 'bid_evaluations', ['evaluated_by'], unique=False)
    op.create_index(op.f('ix_bid_evaluations_id'), 'bid_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_bid_evaluations_recommendation'), 'bid_evaluations', ['recommendation'], unique=False)
    op.create_index(op.f('ix_bid_evaluations_rfp_id'), 'bid_evaluations', ['rfp_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('contract_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('renewal_status', sa.String(length=30), server_default='NOT_DUE', nullable=False),
    sa.Column('contract_status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_account_id'), 'contracts', ['account_id'], unique=False)
    op.create_index(op.f('ix_contracts_contract_number'), 'contracts', ['contract_number'], unique=True)
    op.create_index(op.f('ix_contracts_contract_status'), 'contracts', ['contract_status'], unique=False)
    op.create_index(op.f('ix_contracts_contract_type'), 'contracts', ['contract_type'], unique=False)
    op.create_index(op.f('ix_contracts_end_date'), 'contracts', ['end_date'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_renewal_date'), 'contracts', ['renewal_date'], unique=False)
    op.create_index(op.f('ix_contracts_renewal_status'), 'contracts', ['renewal_status'], unique=False)
    op.create_table('customer_health_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('delivery_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('financial_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('customer_satisfaction_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('sla_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('overall_health_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('health_status', sa.String(length=20), server_default='GREEN', nullable=False),
    sa.Column('risk_reason', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_health_records_account_id'), 'customer_health_records', ['account_id'], unique=False)
    op.create_index(op.f('ix_customer_health_records_health_status'), 'customer_health_records', ['health_status'], unique=False)
    op.create_index(op.f('ix_customer_health_records_id'), 'customer_health_records', ['id'], unique=False)
    op.create_index(op.f('ix_customer_health_records_overall_health_score'), 'customer_health_records', ['overall_health_score'], unique=False)
    op.create_index(op.f('ix_customer_health_records_recorded_at'), 'customer_health_records', ['recorded_at'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_name', sa.String(length=200), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('deal_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('pipeline_stage', sa.String(length=50), server_default='PROSPECTING', nullable=False),
    sa.Column('win_probability', sa.Float(), server_default='0', nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('expected_start_date', sa.Date(), nullable=True),
    sa.Column('sales_owner_id', sa.Integer(), nullable=False),
    sa.Column('presales_owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='OPEN', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['presales_owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_client_name'), 'opportunities', ['client_name'], unique=False)
    op.create_index(op.f('ix_opportunities_expected_close_date'), 'opportunities', ['expected_close_date'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_lead_id'), 'opportunities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_opportunities_opportunity_name'), 'opportunities', ['opportunity_name'], unique=False)
    op.create_index(op.f('ix_opportunities_pipeline_stage'), 'opportunities', ['pipeline_stage'], unique=False)
    op.create_index(op.f('ix_opportunities_presales_owner_id'), 'opportunities', ['presales_owner_id'], unique=False)
    op.create_index(op.f('ix_opportunities_sales_owner_id'), 'opportunities', ['sales_owner_id'], unique=False)
    op.create_index(op.f('ix_opportunities_service_type'), 'opportunities', ['service_type'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_table('rfp_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfp_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assignment_role', sa.String(length=50), nullable=False),
    sa.Column('assignment_status', sa.String(length=30), server_default='ASSIGNED', nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rfp_id'], ['rfps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfp_id', 'user_id', name='uq_rfp_assignment_user')
    )
    op.create_index(op.f('ix_rfp_assignments_assignment_role'), 'rfp_assignments', ['assignment_role'], unique=False)
    op.create_index(op.f('ix_rfp_assignments_assignment_status'), 'rfp_assignments', ['assignment_status'], unique=False)
    op.create_index(op.f('ix_rfp_assignments_id'), 'rfp_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_rfp_assignments_rfp_id'), 'rfp_assignments', ['rfp_id'], unique=False)
    op.create_index(op.f('ix_rfp_assignments_user_id'), 'rfp_assignments', ['user_id'], unique=False)
    op.create_table('partner_deal_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('registration_reference', sa.String(length=150), nullable=True),
    sa.Column('registration_status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('registered_on', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('expected_incentive', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('registered_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_deal_registrations_expiry_date'), 'partner_deal_registrations', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_partner_deal_registrations_id'), 'partner_deal_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_partner_deal_registrations_opportunity_id'), 'partner_deal_registrations', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_partner_deal_registrations_partner_id'), 'partner_deal_registrations', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_deal_registrations_registered_by'), 'partner_deal_registrations', ['registered_by'], unique=False)
    op.create_index(op.f('ix_partner_deal_registrations_registration_reference'), 'partner_deal_registrations', ['registration_reference'], unique=True)
    op.create_index(op.f('ix_partner_deal_registrations_registration_status'), 'partner_deal_registrations', ['registration_status'], unique=False)
    op.create_table('partner_influenced_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('influence_type', sa.String(length=50), nullable=False),
    sa.Column('influenced_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('referral_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tier_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'opportunity_id', name='uq_partner_influenced_opportunity')
    )
    op.create_index(op.f('ix_partner_influenced_opportunities_id'), 'partner_influenced_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_partner_influenced_opportunities_influence_type'), 'partner_influenced_opportunities', ['influence_type'], unique=False)
    op.create_index(op.f('ix_partner_influenced_opportunities_opportunity_id'), 'partner_influenced_opportunities', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_partner_influenced_opportunities_partner_id'), 'partner_influenced_opportunities', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_influenced_opportunities_status'), 'partner_influenced_opportunities', ['status'], unique=False)
    op.create_table('sales_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('activity_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='PLANNED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_activities_activity_date'), 'sales_activities', ['activity_date'], unique=False)
    op.create_index(op.f('ix_sales_activities_activity_type'), 'sales_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_sales_activities_id'), 'sales_activities', ['id'], unique=False)
    op.create_index(op.f('ix_sales_activities_lead_id'), 'sales_activities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_sales_activities_next_follow_up_date'), 'sales_activities', ['next_follow_up_date'], unique=False)
    op.create_index(op.f('ix_sales_activities_opportunity_id'), 'sales_activities', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_sales_activities_status'), 'sales_activities', ['status'], unique=False)
    op.create_index(op.f('ix_sales_activities_user_id'), 'sales_activities', ['user_id'], unique=False)
    op.create_table('solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('solution_name', sa.String(length=200), nullable=False),
    sa.Column('solution_summary', sa.Text(), nullable=True),
    sa.Column('technology_stack', sa.Text(), nullable=True),
    sa.Column('architecture_notes', sa.Text(), nullable=True),
    sa.Column('delivery_model', sa.String(length=50), server_default='OFFSHORE', nullable=False),
    sa.Column('estimated_duration_months', sa.Float(), nullable=True),
    sa.Column('presales_owner_id', sa.Integer(), nullable=False),
    sa.Column('solution_status', sa.String(length=50), server_default='DRAFT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['presales_owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_delivery_model'), 'solutions', ['delivery_model'], unique=False)
    op.create_index(op.f('ix_solutions_id'), 'solutions', ['id'], unique=False)
    op.create_index(op.f('ix_solutions_opportunity_id'), 'solutions', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_solutions_presales_owner_id'), 'solutions', ['presales_owner_id'], unique=False)
    op.create_index(op.f('ix_solutions_solution_name'), 'solutions', ['solution_name'], unique=False)
    op.create_index(op.f('ix_solutions_solution_status'), 'solutions', ['solution_status'], unique=False)
    op.create_table('estimations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('estimation_model', sa.String(length=50), nullable=False),
    sa.Column('resource_cost', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('infrastructure_cost', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('overhead_cost', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('contingency_percentage', sa.Float(), server_default='0', nullable=False),
    sa.Column('contingency_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total_delivery_cost', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('billing_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('expected_profit', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('expected_margin_percentage', sa.Float(), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('approval_status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimations_approval_status'), 'estimations', ['approval_status'], unique=False)
    op.create_index(op.f('ix_estimations_approved_by'), 'estimations', ['approved_by'], unique=False)
    op.create_index(op.f('ix_estimations_estimation_model'), 'estimations', ['estimation_model'], unique=False)
    op.create_index(op.f('ix_estimations_id'), 'estimations', ['id'], unique=False)
    op.create_index(op.f('ix_estimations_solution_id'), 'estimations', ['solution_id'], unique=True)
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('proposal_title', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=30), server_default='1.0', nullable=False),
    sa.Column('sow_document_url', sa.String(length=500), nullable=True),
    sa.Column('proposal_document_url', sa.String(length=500), nullable=True),
    sa.Column('sow_document_filename', sa.String(length=255), nullable=True),
    sa.Column('sow_document_content', sa.LargeBinary(), nullable=True),
    sa.Column('proposal_document_filename', sa.String(length=255), nullable=True),
    sa.Column('proposal_document_content', sa.LargeBinary(), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('proposal_status', sa.String(length=30), server_default='DRAFT', nullable=False),
    sa.Column('approval_status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_approval_status'), 'proposals', ['approval_status'], unique=False)
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=False)
    op.create_index(op.f('ix_proposals_proposal_status'), 'proposals', ['proposal_status'], unique=False)
    op.create_index(op.f('ix_proposals_proposal_title'), 'proposals', ['proposal_title'], unique=False)
    op.create_index(op.f('ix_proposals_solution_id'), 'proposals', ['solution_id'], unique=False)
    op.create_index(op.f('ix_proposals_submission_date'), 'proposals', ['submission_date'], unique=False)
    op.create_table('resource_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('minimum_experience_years', sa.Float(), server_default='0', nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('location_type', sa.String(length=30), server_default='OFFSHORE', nullable=False),
    sa.Column('duration_months', sa.Float(), nullable=True),
    sa.Column('allocation_percentage', sa.Float(), server_default='100', nullable=False),
    sa.Column('cost_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('billing_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('availability_status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_requirements_availability_status'), 'resource_requirements', ['availability_status'], unique=False)
    op.create_index(op.f('ix_resource_requirements_id'), 'resource_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_resource_requirements_location_type'), 'resource_requirements', ['location_type'], unique=False)
    op.create_index(op.f('ix_resource_requirements_role_name'), 'resource_requirements', ['role_name'], unique=False)
    op.create_index(op.f('ix_resource_requirements_skill_name'), 'resource_requirements', ['skill_name'], unique=False)
    op.create_index(op.f('ix_resource_requirements_solution_id'), 'resource_requirements', ['solution_id'], unique=False)
    op.create_table('blended_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimation_id', sa.Integer(), nullable=False),
    sa.Column('location_type', sa.String(length=30), nullable=False),
    sa.Column('resource_ratio', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('bill_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['estimation_id'], ['estimations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blended_rates_estimation_id'), 'blended_rates', ['estimation_id'], unique=False)
    op.create_index(op.f('ix_blended_rates_id'), 'blended_rates', ['id'], unique=False)
    op.create_index(op.f('ix_blended_rates_location_type'), 'blended_rates', ['location_type'], unique=False)
    op.create_table('financial_actuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('estimation_id', sa.Integer(), nullable=True),
    sa.Column('billing_milestone', sa.String(length=150), nullable=True),
    sa.Column('milestone_date', sa.Date(), nullable=True),
    sa.Column('actual_revenue', sa.Numeric(precision=16, scale=2), server_default='0', nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=16, scale=2), server_default='0', nullable=False),
    sa.Column('actual_profit', sa.Numeric(precision=16, scale=2), server_default='0', nullable=False),
    sa.Column('actual_margin_percentage', sa.Numeric(precision=7, scale=2), server_default='0', nullable=False),
    sa.Column('projected_margin_percentage', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('margin_variance', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('timesheet_utilization_percentage', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='INR', nullable=False),
    sa.Column('source_system', sa.String(length=50), server_default='CSV_IMPORT', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['estimation_id'], ['estimations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_actuals_account_id'), 'financial_actuals', ['account_id'], unique=False)
    op.create_index(op.f('ix_financial_actuals_contract_id'), 'financial_actuals', ['contract_id'], unique=False)
    op.create_index(op.f('ix_financial_actuals_estimation_id'), 'financial_actuals', ['estimation_id'], unique=False)
    op.create_index(op.f('ix_financial_actuals_id'), 'financial_actuals', ['id'], unique=False)
    op.create_index(op.f('ix_financial_actuals_milestone_date'), 'financial_actuals', ['milestone_date'], unique=False)
    op.create_index(op.f('ix_financial_actuals_opportunity_id'), 'financial_actuals', ['opportunity_id'], unique=False)
    op.create_table('resource_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=True),
    sa.Column('requested_role', sa.String(length=100), nullable=False),
    sa.Column('required_skill', sa.String(length=100), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('minimum_experience_years', sa.Float(), server_default='0', nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('required_from', sa.Date(), nullable=False),
    sa.Column('required_until', sa.Date(), nullable=True),
    sa.Column('allocation_percentage', sa.Float(), server_default='100', nullable=False),
    sa.Column('location_type', sa.String(length=30), nullable=True),
    sa.Column('request_status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resource_requirement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_requirement_id'], ['resource_requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_requests_id'), 'resource_requests', ['id'], unique=False)
    op.create_index(op.f('ix_resource_requests_location_type'), 'resource_requests', ['location_type'], unique=False)
    op.create_index(op.f('ix_resource_requests_opportunity_id'), 'resource_requests', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_resource_requests_request_status'), 'resource_requests', ['request_status'], unique=False)
    op.create_index(op.f('ix_resource_requests_requested_by'), 'resource_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_resource_requests_requested_role'), 'resource_requests', ['requested_role'], unique=False)
    op.create_index(op.f('ix_resource_requests_required_from'), 'resource_requests', ['required_from'], unique=False)
    op.create_index(op.f('ix_resource_requests_required_skill'), 'resource_requests', ['required_skill'], unique=False)
    op.create_index(op.f('ix_resource_requests_required_until'), 'resource_requests', ['required_until'], unique=False)
    op.create_index(op.f('ix_resource_requests_resource_requirement_id'), 'resource_requests', ['resource_requirement_id'], unique=True)
    op.create_index(op.f('ix_resource_requests_solution_id'), 'resource_requests', ['solution_id'], unique=False)
    op.create_table('resource_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('solution_id', sa.Integer(), nullable=True),
    sa.Column('resource_request_id', sa.Integer(), nullable=True),
    sa.Column('allocation_type', sa.String(length=30), server_default='SOFT_BOOKING', nullable=False),
    sa.Column('allocation_percentage', sa.Float(), server_default='100', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('allocation_status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('allocated_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['allocated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_request_id'], ['resource_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_allocations_allocated_by'), 'resource_allocations', ['allocated_by'], unique=False)
    op.create_index(op.f('ix_resource_allocations_allocation_status'), 'resource_allocations', ['allocation_status'], unique=False)
    op.create_index(op.f('ix_resource_allocations_allocation_type'), 'resource_allocations', ['allocation_type'], unique=False)
    op.create_index(op.f('ix_resource_allocations_employee_id'), 'resource_allocations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_resource_allocations_end_date'), 'resource_allocations', ['end_date'], unique=False)
    op.create_index(op.f('ix_resource_allocations_id'), 'resource_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_resource_allocations_opportunity_id'), 'resource_allocations', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_resource_allocations_resource_request_id'), 'resource_allocations', ['resource_request_id'], unique=False)
    op.create_index(op.f('ix_resource_allocations_solution_id'), 'resource_allocations', ['solution_id'], unique=False)
    op.create_index(op.f('ix_resource_allocations_start_date'), 'resource_allocations', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_allocations_start_date'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_solution_id'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_resource_request_id'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_opportunity_id'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_id'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_end_date'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_employee_id'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_allocation_type'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_allocation_status'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_allocated_by'), table_name='resource_allocations')
    op.drop_table('resource_allocations')
    op.drop_index(op.f('ix_resource_requests_solution_id'), table_name='resource_requests')
    op.drop_index(op.f('ix_resource_requests_resource_requirement_id'), table_name='resource_requests')
    op.drop_index(op.f('ix_resource_requests_required_until'), table_name='resource_requests')
    op.drop_index(op.f('ix_resource_requests_required_skill'), table_name='resource_requests')
    op.drop_index(op.f('ix_resource_requests_required_from'), table_name='resource_requests')
    op.drop_index(op.f('ix_resource_requests_requested_role'), table_name='resource_requests')
    op.drop_index(op.f('ix_resource_requests_requested_by'), table_name='resource_requests')
    op.drop_index(op.f('ix_resource_requests_request_status'), table_name='resource_requests')
    op.drop_index(op.f('ix_resource_requests_opportunity_id'), table_name='resource_requests')
    op.drop_index(op.f('ix_resource_requests_location_type'), table_name='resource_requests')
    op.drop_index(op.f('ix_resource_requests_id'), table_name='resource_requests')
    op.drop_table('resource_requests')
    op.drop_index(op.f('ix_financial_actuals_opportunity_id'), table_name='financial_actuals')
    op.drop_index(op.f('ix_financial_actuals_milestone_date'), table_name='financial_actuals')
    op.drop_index(op.f('ix_financial_actuals_id'), table_name='financial_actuals')
    op.drop_index(op.f('ix_financial_actuals_estimation_id'), table_name='financial_actuals')
    op.drop_index(op.f('ix_financial_actuals_contract_id'), table_name='financial_actuals')
    op.drop_index(op.f('ix_financial_actuals_account_id'), table_name='financial_actuals')
    op.drop_table('financial_actuals')
    op.drop_index(op.f('ix_blended_rates_location_type'), table_name='blended_rates')
    op.drop_index(op.f('ix_blended_rates_id'), table_name='blended_rates')
    op.drop_index(op.f('ix_blended_rates_estimation_id'), table_name='blended_rates')
    op.drop_table('blended_rates')
    op.drop_index(op.f('ix_resource_requirements_solution_id'), table_name='resource_requirements')
    op.drop_index(op.f('ix_resource_requirements_skill_name'), table_name='resource_requirements')
    op.drop_index(op.f('ix_resource_requirements_role_name'), table_name='resource_requirements')
    op.drop_index(op.f('ix_resource_requirements_location_type'), table_name='resource_requirements')
    op.drop_index(op.f('ix_resource_requirements_id'), table_name='resource_requirements')
    op.drop_index(op.f('ix_resource_requirements_availability_status'), table_name='resource_requirements')
    op.drop_table('resource_requirements')
    op.drop_index(op.f('ix_proposals_submission_date'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_solution_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_proposal_title'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_proposal_status'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_approval_status'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_estimations_solution_id'), table_name='estimations')
    op.drop_index(op.f('ix_estimations_id'), table_name='estimations')
    op.drop_index(op.f('ix_estimations_estimation_model'), table_name='estimations')
    op.drop_index(op.f('ix_estimations_approved_by'), table_name='estimations')
    op.drop_index(op.f('ix_estimations_approval_status'), table_name='estimations')
    op.drop_table('estimations')
    op.drop_index(op.f('ix_solutions_solution_status'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_solution_name'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_presales_owner_id'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_opportunity_id'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_id'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_delivery_model'), table_name='solutions')
    op.drop_table('solutions')
    op.drop_index(op.f('ix_sales_activities_user_id'), table_name='sales_activities')
    op.drop_index(op.f('ix_sales_activities_status'), table_name='sales_activities')
    op.drop_index(op.f('ix_sales_activities_opportunity_id'), table_name='sales_activities')
    op.drop_index(op.f('ix_sales_activities_next_follow_up_date'), table_name='sales_activities')
    op.drop_index(op.f('ix_sales_activities_lead_id'), table_name='sales_activities')
    op.drop_index(op.f('ix_sales_activities_id'), table_name='sales_activities')
    op.drop_index(op.f('ix_sales_activities_activity_type'), table_name='sales_activities')
    op.drop_index(op.f('ix_sales_activities_activity_date'), table_name='sales_activities')
    op.drop_table('sales_activities')
    op.drop_index(op.f('ix_partner_influenced_opportunities_status'), table_name='partner_influenced_opportunities')
    op.drop_index(op.f('ix_partner_influenced_opportunities_partner_id'), table_name='partner_influenced_opportunities')
    op.drop_index(op.f('ix_partner_influenced_opportunities_opportunity_id'), table_name='partner_influenced_opportunities')
    op.drop_index(op.f('ix_partner_influenced_opportunities_influence_type'), table_name='partner_influenced_opportunities')
    op.drop_index(op.f('ix_partner_influenced_opportunities_id'), table_name='partner_influenced_opportunities')
    op.drop_table('partner_influenced_opportunities')
    op.drop_index(op.f('ix_partner_deal_registrations_registration_status'), table_name='partner_deal_registrations')
    op.drop_index(op.f('ix_partner_deal_registrations_registration_reference'), table_name='partner_deal_registrations')
    op.drop_index(op.f('ix_partner_deal_registrations_registered_by'), table_name='partner_deal_registrations')
    op.drop_index(op.f('ix_partner_deal_registrations_partner_id'), table_name='partner_deal_registrations')
    op.drop_index(op.f('ix_partner_deal_registrations_opportunity_id'), table_name='partner_deal_registrations')
    op.drop_index(op.f('ix_partner_deal_registrations_id'), table_name='partner_deal_registrations')
    op.drop_index(op.f('ix_partner_deal_registrations_expiry_date'), table_name='partner_deal_registrations')
    op.drop_table('partner_deal_registrations')
    op.drop_index(op.f('ix_rfp_assignments_user_id'), table_name='rfp_assignments')
    op.drop_index(op.f('ix_rfp_assignments_rfp_id'), table_name='rfp_assignments')
    op.drop_index(op.f('ix_rfp_assignments_id'), table_name='rfp_assignments')
    op.drop_index(op.f('ix_rfp_assignments_assignment_status'), table_name='rfp_assignments')
    op.drop_index(op.f('ix_rfp_assignments_assignment_role'), table_name='rfp_assignments')
    op.drop_table('rfp_assignments')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_service_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_sales_owner_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_presales_owner_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_pipeline_stage'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_opportunity_name'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_lead_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_expected_close_date'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_client_name'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_customer_health_records_recorded_at'), table_name='customer_health_records')
    op.drop_index(op.f('ix_customer_health_records_overall_health_score'), table_name='customer_health_records')
    op.drop_index(op.f('ix_customer_health_records_id'), table_name='customer_health_records')
    op.drop_index(op.f('ix_customer_health_records_health_status'), table_name='customer_health_records')
    op.drop_index(op.f('ix_customer_health_records_account_id'), table_name='customer_health_records')
    op.drop_table('customer_health_records')
    op.drop_index(op.f('ix_contracts_renewal_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_renewal_date'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_end_date'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_type'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_number'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_account_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_bid_evaluations_rfp_id'), table_name='bid_evaluations')
    op.drop_index(op.f('ix_bid_evaluations_recommendation'), table_name='bid_evaluations')
    op.drop_index(op.f('ix_bid_evaluations_id'), table_name='bid_evaluations')
    op.drop_index(op.f('ix_bid_evaluations_evaluated_by'), table_name='bid_evaluations')
    op.drop_table('bid_evaluations')
    op.drop_index(op.f('ix_account_opportunities_status'), table_name='account_opportunities')
    op.drop_index(op.f('ix_account_opportunities_service_type'), table_name='account_opportunities')
    op.drop_index(op.f('ix_account_opportunities_opportunity_name'), table_name='account_opportunities')
    op.drop_index(op.f('ix_account_opportunities_id'), table_name='account_opportunities')
    op.drop_index(op.f('ix_account_opportunities_expected_close_date'), table_name='account_opportunities')
    op.drop_index(op.f('ix_account_opportunities_created_by'), table_name='account_opportunities')
    op.drop_index(op.f('ix_account_opportunities_account_id'), table_name='account_opportunities')
    op.drop_table('account_opportunities')
    op.drop_index(op.f('ix_rfps_title'), table_name='rfps')
    op.drop_index(op.f('ix_rfps_submission_deadline'), table_name='rfps')
    op.drop_index(op.f('ix_rfps_service_type'), table_name='rfps')
    op.drop_index(op.f('ix_rfps_rfp_status'), table_name='rfps')
    op.drop_index(op.f('ix_rfps_rfp_number'), table_name='rfps')
    op.drop_index(op.f('ix_rfps_received_date'), table_name='rfps')
    op.drop_index(op.f('ix_rfps_owner_id'), table_name='rfps')
    op.drop_index(op.f('ix_rfps_id'), table_name='rfps')
    op.drop_index(op.f('ix_rfps_client_name'), table_name='rfps')
    op.drop_index(op.f('ix_rfps_bid_decision'), table_name='rfps')
    op.drop_table('rfps')
    op.drop_index(op.f('ix_presales_templates_template_name'), table_name='presales_templates')
    op.drop_index(op.f('ix_presales_templates_service_type'), table_name='presales_templates')
    op.drop_index(op.f('ix_presales_templates_id'), table_name='presales_templates')
    op.drop_index(op.f('ix_presales_templates_created_by'), table_name='presales_templates')
    op.drop_table('presales_templates')
    op.drop_index(op.f('ix_leads_priority'), table_name='leads')
    op.drop_index(op.f('ix_leads_next_follow_up_date'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_contact_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_sales_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_accounts_sla_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_risk_level'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_primary_contact_email'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_industry'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_customer_health_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_director_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_partner_certifications_partner_id'), table_name='partner_certifications')
    op.drop_index(op.f('ix_partner_certifications_is_active'), table_name='partner_certifications')
    op.drop_index(op.f('ix_partner_certifications_id'), table_name='partner_certifications')
    op.drop_index(op.f('ix_partner_certifications_expiry_date'), table_name='partner_certifications')
    op.drop_index(op.f('ix_partner_certifications_employee_id'), table_name='partner_certifications')
    op.drop_index(op.f('ix_partner_certifications_certification_name'), table_name='partner_certifications')
    op.drop_table('partner_certifications')
    op.drop_index(op.f('ix_employee_skills_skill_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_proficiency_level'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_employee_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_certification_expiry_date'), table_name='employee_skills')
    op.drop_table('employee_skills')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_partners_partner_type'), table_name='partners')
    op.drop_index(op.f('ix_partners_partner_tier'), table_name='partners')
    op.drop_index(op.f('ix_partners_name'), table_name='partners')
    op.drop_index(op.f('ix_partners_id'), table_name='partners')
    op.drop_index(op.f('ix_partners_contact_email'), table_name='partners')
    op.drop_table('partners')
    op.drop_index(op.f('ix_executive_kpi_snapshots_snapshot_month'), table_name='executive_kpi_snapshots')
    op.drop_index(op.f('ix_executive_kpi_snapshots_id'), table_name='executive_kpi_snapshots')
    op.drop_table('executive_kpi_snapshots')
    op.drop_index(op.f('ix_employees_location'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_full_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_employment_type'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_designation'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_index(op.f('ix_employees_available_from'), table_name='employees')
    op.drop_index(op.f('ix_employees_availability_status'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
